adding debugging logs

diff --git a/.github/workflows/update-data.yml b/.github/workflows/update-data.yml
--- a/.github/workflows/update-data.yml
+++ b/.github/workflows/update-data.yml
@@ -60,8 +60,17 @@ jobs:
         env:
           FORMATTER_INPUT_FOLDER: ${{ github.workspace }}/_data/${{ env.STATE }}
           SCRAPER_TEMP_DATA: $${{ runner.temp }}/_working/_data/${{ env.STATE }}
+          POSSIBLE_OTHER: $${{ runner.temp }}/_data/${{ env.STATE }}
         run: |
           mkdir -p $FORMATTER_INPUT_FOLDER
+          echo "Checking for folders existance"
+          echo "FORMATTER_INPUT_FOLDER"
+          ls -la "$FORMATTER_INPUT_FOLDER" || echo "❌ FORMATTER_INPUT_FOLDER not found"
+          echo "SCRAPER_TEMP_DATA"
+          ls -la "$SCRAPER_TEMP_DATA" || echo "❌ SCRAPER_TEMP_DATA not found"
+          echo "POSSIBLE_OTHER"
+          ls -la "$SPOSSIBLE_OTHER" || echo "❌ POSSIBLE_OTHER not found"
+          
           cp -r $SCRAPER_TEMP_DATA/* $FORMATTER_INPUT_FOLDER
           pip install pipenv
           pipenv install
